### ISSUE TITLE
Flutter@Build not working

### ISSUE THREAD

**Issue by ochamods** [hey24sheep/azure-flutter-tasks#1]
Task fails when generating APK it gets stuck with the following error: 

![image](https://user-images.githubusercontent.com/68409599/126271389-113a4b84-00a1-4b7f-b4d4-076838d4a708.png)

That doesn't say much, Has anybody else experienced this problem?

This is the configuration for the Build task:

![image](https://user-images.githubusercontent.com/68409599/126271474-1c2f0115-e855-4786-a596-5ec3b13145f0.png)

Is it because I am using flavors?

**Comment by hey24sheep** [comment]
Does your code build locally, with version 2.2.2-stable?

**Comment by ochamods** [comment]
Yes, I have that version installed in my PC.

**Comment by hey24sheep** [comment]
Can you test the same on a Mac? As your build is on a Mac vm. Without any error response it's hard to help. Can you also try building using Task Flutter Command instead of Flutter Build and see if it's a build command issue.

**Comment by ochamods** [comment]
Oh yeah I have the same version in the Mac and it works fine. 

How I should set the config for Flutter Task Command, could you give an example for it please?

**Comment by hey24sheep** [comment]
You give project directory and your build argument like "flutter build apk" or whatever command you use locally. Refer to Readme as well for more info. Try --verbose as well maybe it will show the error.

**Comment by ochamods** [comment]
It worked with the following command:
`flutter build apk --verbose --flavor prod`

And continues to fail with the Build task so I removed it.

**Comment by hey24sheep** [comment]
Well, I am glad it worked with command line. But that's so weird :/ it is failing with build task. Can you give me the command build task generates here, is it the same as your command line one?

**Comment by ochamods** [comment]
I would love to do it but it never prints the command when using the build task, it only displays the error in the first image :/. It seems like it gets stuck when entering to the Build task stage.

![image](https://user-images.githubusercontent.com/68409599/126521793-85c57d8d-2281-4fcb-8a71-27c4f886f1bf.png)

**Comment by hey24sheep** [comment]
I will keep this issue open for a while, if anyone else facing this issue.

**Comment by gabrielglbh** [comment]
I am working with this in my job, and I am facing the same issue as @ochamods. It seems that the command runs well.

**Comment by hey24sheep** [comment]
I can show you my config which is working in our envs for target:apk. Mine is a lil different as we build only arm64 and have build flavours setup. We do not use .yml setup definition instead we use GUI from the Pipeline build setup. 

You could try setting your build task using Pipeline GUI once and see if it works. Also, try this [enable pipeline diagnostics](https://docs.microsoft.com/en-us/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops) and then run your Build task and see what command and error (if any) it throws.

``` yaml
//# Flutter Install 
steps:
- task: Hey24sheep.flutter.flutter-install.FlutterInstall@0
  displayName: 'Flutter Install'
  inputs:
    version: custom
    customVersion: 1.22.6

//# Flutter Build
steps:
- task: Hey24sheep.flutter.flutter-build.FlutterBuild@0
  displayName: 'Flutter Build apk'
  inputs:
    projectDirectory: myProject
    debugMode: true
    buildFlavour: development
    entryPoint: 'lib/main_dev.dart'
    apkTargetPlatform: 'android-arm64' 
```

**Comment by hey24sheep** [comment]
> Is it because I am using flavors?

@ochamods I missed your statement somehow. Looking at your yaml, you are missing the 'entryPoint' as you are using Flavours, don't you need it in command line? It should fail without `--target` if `--flavor` is given, doesn't it on latest Flutter?

**Comment by hey24sheep** [comment]
Could you guys check on the latest version if this is issue is there or not? Otherwise, this issue will be closed as there as been many major updates since then.

You can track the changes [here](https://github.com/hey24sheep/azure-flutter-tasks/blob/master/CHANGELOG.md).

**Comment by okayestdeveloper** [comment]
I hit a failure with FlutterBuild while working on our pipeline. I'm not sure if it's the same, but here's what is happening to me.
My command:
```
      - task: FlutterBuild@0
        displayName: 'Build for iOS and Android'
        inputs:
          target: 'mobile'
          projectDirectory: $(projectDirectory)
          verboseMode: true
          debugMode: true
```

I can attach the full log if needed, but this appears to be the only non-zero exit code (thus failing the pipeline)
```
2022-02-11T20:37:21.7420730Z [ +170 ms] executing: sysctl hw.optional.arm64
2022-02-11T20:37:21.7493670Z [  +30 ms] Exit code 1 from: sysctl hw.optional.arm64
2022-02-11T20:37:21.7498710Z [        ] sysctl: unknown oid 'hw.optional.arm64'
```
