### ISSUE TITLE
If flavour is specified, it must be passed through to the flutter build command

### ISSUE THREAD

**Issue by guulp** [hey24sheep/azure-flutter-tasks#103]
The flavour is necessary whether or not this is a simulator build or not. This line should be removed. If your build configuration settings use flavours then you always need to specify them:

https://github.com/hey24sheep/azure-flutter-tasks/blob/92e259d8763420579341240ecf29e60c22d5d8a0/tasks/build/index.ts#L430

**Comment by hey24sheep** [comment]
That might be the part of the new Flutter build, on older versions of Flutter it was not the case. But, we can remove the simulator check and have it add build flavor if it is given by the user.

I'll need sometime to work on it as I am quite busy.

**Comment by guulp** [comment]
Sure, and thanks for creating this task to begin with.

My current workaround is:
```
  - task: Hey24sheep.flutter.flutter-build.FlutterBuild@0
    displayName: 'Build ${{parameters.flavour}}'
    inputs:
      buildFlavour: '${{parameters.flavour}}'
      verboseMode: true
......
      extraArgs: '--simulator'
```
