### ISSUE TITLE
How do I run latest version in Azure Pipeline Task?

### ISSUE THREAD

**Issue by aguilita1** [hey24sheep/azure-flutter-tasks#123]
How do I run latest version in Azure Pipeline Task?  I know this should be super simple but I have not been able to figure it out.

Here is an example of task.

```
- task: FlutterCommand@0
  displayName: "Run packages"
  inputs:
    arguments: 'packages pub run build_runner build'
    projectDirectory: 'revolve_wellness_studios'
```

Output from log shows version 0.3.2 running
```
Starting: Run packages
==============================================================================
Task         : Flutter Command Task
Description  : Launch a custom Flutter command with custom arguments.
Version      : 0.3.2
Author       : Hey24sheep
Help         : Don't forget to insert a 'Flutter Install' task before. [More Information](https://github.com/hey24sheep/azure-flutter-tasks)
==============================================================================

```
