### ISSUE TITLE
More fun with build numbers

### ISSUE THREAD

**Issue by bobwiller** [hey24sheep/azure-flutter-tasks#13]
For the life of me I cannot get revision numbers to appear in the build number for ios.  The top of my pipeline looks like this:

![image](https://user-images.githubusercontent.com/2389999/135311413-fe159702-cbe1-44d9-aa99-f630902e5eb1.png)

The echo does what I would expect, which produces: `echo '20210929.10'`

Then my build step a bit further down:
![image](https://user-images.githubusercontent.com/2389999/135311980-5fce4d34-19e8-4624-a385-685800320579.png)

No matter what I seem to try, i only get the date portion on the build:
`/Users/runner/hostedtoolcache/Flutter/2.5.1-stable/macos/flutter/bin/flutter build ios --no-codesign --build-number=20210929`

Does anyone have revision numbers working?
Thanks,
Bob

**Comment by hey24sheep** [comment]
Flutter doesn't allow decimals for `--build-number`, check issue #10. In response I have added a safety check in code which strips out the decimal value (as Flutter doesn't allow decimal values) so the build doesn't fail.

**Comment by hey24sheep** [comment]
You could check [this](https://stackoverflow.com/questions/63391384/strange-build-error-in-azure-devops-while-using-flutter). If you want to have a proper versioning, check out this [medium article](https://medium.com/karlmax-berlin/versioning-with-flutter-299869e68af4). In regard to this, you can setup your Azure environment accordingly and pass `buildNumber` & `buildName` to the "Build Task".

If this solves your problem, don't forget to close the issue :)

**Comment by bobwiller** [comment]
Thx @hey24sheep - that is helpful.  I believe (and others can correct me if I am wrong) it is only Android that does not allow decimals - they are fine w/ios, but I am all about being consistent.  Appreciate the reply.

**Comment by zliebersbach** [comment]
I just fell into this trap, I do not think stripping out the decimal is the solution here because it means your pipeline might create a build where the version code has already been taken. e.g. multiple builds in one day will all produce the same version code without the decimal. I think the pipeline should raise an error if the buildNumber includes a decimal, and in the [README](https://github.com/hey24sheep/azure-flutter-tasks/blob/master/README.md) it should recommend to use `$(Build.BuildId)` instead.

**Comment by hey24sheep** [comment]
@zliebersbach `e.g. multiple builds in one day will all produce the same version code without the decimal`, this won't happen if industry standards are being used. Generally the "build number" of the running build is available in Environment which is used as a "Patch" version to increment the build, so every deployment is always new number based on dynamic build numbers generated by Azure. 

If for some reason there is some custom versioning going on "assuming not using Flutter guidelines". Then you can have a "powershell/bash" script to manually increment the "pubspec" or IOS pod file code to next integer value.

**Comment by zliebersbach** [comment]
@hey24sheep I think I worded it incorrectly, FYI we use the default out-of-the-box build number provided by DevOps (e.g. first build of the day: 20230228, second build of the day: 20230228.1, etc.). The proposed "solution" of simply truncating the revision number (decimal) from build means that you will have version code conflicts if you need to upload two builds in one day to the same channel. Does that make sense?

**Comment by hey24sheep** [comment]
@zliebersbach You were clear, I understood that. But maybe I wasn't, in terms of [Flutter Versioning](https://medium.com/karlmax-berlin/versioning-with-flutter-299869e68af4), second build of the day would be 20230228+1, anything "+123" will be the patch. Decimal is not allowed for "+123" (versionCode). 

Also to clarify a little on why decimal is stripped out and I hope you understand my choice, 
- Both of these "buildNumber" and "buildName" are optional. So, if someone is using Flutter Auto Increment, they are good to go
- I cannot validate decimal at UI/UX level because these values are taken as "string" and Azure SDK doesn't provide a dynamic input validator (or am I missing something maybe) while user is typing input.
- Big assumption is made that users are aware of no decimal Flutter versioning guideline
- This extension is used by over 3000 people on Azure, I do not want to fail/break pipelines of that many people. So, to save from that we silently fix the issue in case user is unaware. Also, I do not want to waste 1 build cycle time for most people running 1 deployment per day by throwing runtime error

Just for reference, this is how we manually increment builds on old Flutter 1.7 "non auto increment" build.

```yaml
steps:
- powershell: |
   $date=$(Get-Date -Format yyyy.MM.dd);
   Write-Host "##vso[task.setvariable variable=buildTimeStamp]$date"
   
  displayName: 'Get Runtime Date for Version Update (yyyy.mm.dd)'
```

```yaml
steps:
- task: Hey24sheep.flutter.flutter-build.FlutterBuild@0
  displayName: 'Flutter Build apk'
  inputs:
    projectDirectory: buildsys
    verboseMode: true
    buildFlavour: development
    buildNumber: '$(Build.BuildNumber)'
    buildName: '$(buildTimeStamp)'
    entryPoint: 'lib/main_dev.dart'
    apkTargetPlatform: 'android-arm64'
    extraArgs: '--no-tree-shake-icons'
```
