### ISSUE TITLE
integration_test support

### ISSUE THREAD

**Issue by neiljaywarner** [hey24sheep/azure-flutter-tasks#24]
Do you have ideas on runnning integration tests in our Azure pipeline .

I've done this sort of thing before on a Jenkins pipeline i just don't have it handy, but essentially opening a simulator with open -a simulator, possibly creating it etc.

**Comment by hey24sheep** [comment]
Have a look at [this](https://medium.com/flutter-community/ui-tests-in-flutter-with-azure-pipelines-c86dea44a0c2). This might help you.

**Comment by maksymgendin** [comment]
@hey24sheep According to the [official documentation](https://docs.flutter.dev/cookbook/testing/integration/introduction#5a-mobile) the commands for running the mobile integration tests could be:
```
flutter test integration_test/app_test.dart         # specific test
flutter test integration_test                       # all tests in folder
```
How would you trigger these commands with [your test task definition](https://github.com/hey24sheep/azure-flutter-tasks#test)?

**Comment by hey24sheep** [comment]
This is how you use it. It will generate a command `flutter test --pub` which will auto run all tests. 

If you want to run a specific test use `testPlainName` this arg.

```yaml
steps:
  - task: Hey24sheep.flutter.flutter-test.FlutterTest@0
    displayName: 'Flutter Test'
    inputs:
      projectDirectory: <flutter_project_directory or $(projectDirectory) if it is an environment variable> 
```

**Comment by maksymgendin** [comment]
@hey24sheep I understand. That means, writing
```yaml
steps:
  - task: Hey24sheep.flutter.flutter-test.FlutterTest@0
    displayName: 'Flutter Test'
    inputs:
      ...
      testPlainName: integration_test
```
would generate
```
flutter test integration_test
```
as command and execute all integration tests under the folder `integration_test`. Correct?

BTW: What does `--pub` do? Couldn't find this argument in the docs.
