### ISSUE TITLE
Install dart applications

### ISSUE THREAD

**Issue by KarlChow92** [hey24sheep/azure-flutter-tasks#36]
Hello,

I am trying to install a dart application through dart pub global activate. However, I cannot reference it back. 

Hereby my configuration:
Mac OS 11.6.5
hey24sheep/azure-flutter-task 0.3.0
Flutter 2.10.3

Please see the image below where I simply use: 
```
- task: CmdLine@2
        displayName: "👩🏻‍🏫 Installing dart tools"
        inputs:
          script: "$(FlutterToolPath)/dart pub global activate junitreport"
```
![image](https://user-images.githubusercontent.com/2989224/163365979-444a56c9-c2de-490d-aa82-03631259929e.png)

After that I am then running:
```
- task: CmdLine@2
        displayName: "👨🏻‍🏫 Test"
        inputs:
          script: "$(FlutterToolPath)/flutter test --coverage --no-test-assets --no-sound-null-safety --machine >> test_result.json"
          workingDirectory: "."
```

This assures that the test results are being saved in a json format which I then want to convert with `junitreport` to a junit report so that it wil be visible in Azure. 

This happens through: 
```
- task: CmdLine@2
        displayName: "👨🏻‍🏫 Test"
        inputs:
          script: "$(FlutterPubCachePath)/tojunit -i test_result.json -o test_result.xml"
          workingDirectory: "."
```

![image](https://user-images.githubusercontent.com/2989224/163366014-b2243f3b-ab3a-4507-bd8f-09fa66081eb8.png)

However, the last step fails, do you have any idea why? 

Thanks!
