### ISSUE TITLE
iOS Example

### ISSUE THREAD

**Issue by mswilson4040** [hey24sheep/azure-flutter-tasks#37]
I see that there is an Android example within the [azure-pipelines.yml](https://github.com/hey24sheep/azure-flutter-tasks/blob/master/azure-pipelines.yml) file. Could we get an iOS equivillant?

**Comment by hey24sheep** [comment]
Hi, I do not have a mac machine. It is hard to create a yml file for iOS. IOS uses a lot of other 3rd party tasks along with Flutter. We use a very old Flutter version so I do not know how IPA build works.

Here is a sample ios build config. After this step there are a few more steps of using [Apple provising install and cert install tasks](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/install-apple-provisioning-profile?view=azure-devops)
```
steps:
- task: Hey24sheep.flutter.flutter-build.FlutterBuild@0
  displayName: 'Flutter Build ios'
  inputs:
    target: ios
    projectDirectory: <your project>
    buildFlavour: <flavour>
    buildNumber: '$(Build.BuildNumber)'
    buildName: '$(buildTimeStamp)'
    entryPoint: 'lib/main_dev.dart'
    iosCodesign: false
    extraArgs: '--no-tree-shake-icons'
```

We build archive using this command
`xcodebuild -exportArchive -archivePath Runner.xcarchive -exportPath Runner -exportOptionsPlist ios/export_dev.plist`

I would really appreciate if anyone from the community can add a PR or a comment here for a nice clean yml config.

**Comment by xeladu** [comment]
I have created a simple pipeline that works for iOS (with additional configuration steps) -> https://xeladu.medium.com/building-flutter-apps-with-azure-devops-eaf9ae7ad158?sk=dcdc007ae2c4fab7942ec5108f189c9a

Here is a working pipeline for iOS and Android:

```
trigger:
  - master

pool:
  vmImage: macOS-11

stages:
- stage: AndroidStage
  dependsOn: []
  displayName: Android
  jobs:

  - job: AndroidJob
    displayName: Android
    steps: 

    - task: DownloadSecureFile@1
      name: keyprop
      displayName: Download key properties file
      inputs:
        secureFile: 'key.properties'

    - task: DownloadSecureFile@1
      name: key
      displayName: Download signing key
      inputs:
        secureFile: 'key.jks'

    - task: Bash@3
      displayName: Copy config files
      inputs:
        targetType: 'inline'
        script: |
          cp $(keyprop.secureFilePath) $(Build.SourcesDirectory)/android/key.properties
          cp $(key.secureFilePath) $(Build.SourcesDirectory)/android/app/key.jks
          
          echo "key.properties copied to $(Build.SourcesDirectory)/android/key.properties"
          echo "key.jks copied to $(Build.SourcesDirectory)/android/app/key.jks"

    - task: FlutterInstall@0
      displayName: "Install Flutter SDK"
      inputs:
        mode: 'auto'
        channel: 'stable'
        version: 'latest'

    - task: FlutterBuild@0
      displayName: "Build application"
      inputs:
        target: 'aab'
        projectDirectory: '$(Build.SourcesDirectory)'

    - task: FlutterTest@0
      displayName: "Run unit tests"
      inputs:
        generateCodeCoverageReport: true
        projectDirectory: '$(Build.SourcesDirectory)'

    - task: CopyFiles@2
      displayName: "Copy app to staging directory"
      inputs:
        sourceFolder: '$(Agent.BuildDirectory)'
        contents: '**/bundle/**'
        targetFolder: '$(Build.StagingDirectory)'
        flattenFolders: true

    - task: PublishBuildArtifacts@1
      displayName: "Publish AAB file"
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'AAB'
        publishLocation: 'Container'

- stage: iOSStage
  dependsOn: []
  displayName: iOS
  jobs:
 
  - job: iOSJob
    displayName: iOS
    steps: 
          
    - task: InstallAppleCertificate@2
      displayName: Install certificate
      inputs:
        certSecureFile: 'iosKey'
        certPwd: 'yourPwd'
        keychain: 'temp'
    
    - task: InstallAppleProvisioningProfile@1
      displayName: Install provisioning file
      inputs:
        provisioningProfileLocation: 'secureFiles'
        provProfileSecureFile: 'ios_Profile.mobileprovision'
        
    - task: FlutterInstall@0
      displayName: "Install Flutter SDK"
      inputs:
        mode: 'auto'
        channel: 'stable'
        version: 'latest'

    - task: FlutterBuild@0
      displayName: "Build application"
      inputs:
        target: ipa
        projectDirectory: '$(Build.SourcesDirectory)'
        exportOptionsPlist: 'ios/exportOptions.plist'

    - task: FlutterTest@0
      displayName: "Run unit tests"
      inputs:
        generateCodeCoverageReport: true
        projectDirectory: '$(Build.SourcesDirectory)'

    - task: CopyFiles@2
      displayName: "Copy app to staging directory"
      inputs:
        sourceFolder: '$(Agent.BuildDirectory)'
        contents: '**/ipa/*.ipa'
        targetFolder: '$(Build.StagingDirectory)'
        flattenFolders: true

    - task: PublishBuildArtifacts@1
      displayName: "Publish IPA file"
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'IPA'
        publishLocation: 'Container'

**Comment by hey24sheep** [comment]
@xeladu Hi, thank you for a great Medium guide and a clean yaml file. I have added the same to the readme FAQs as well as created a [wiki ](https://github.com/hey24sheep/azure-flutter-tasks/wiki/IOS-&-Android-Example-Setup-Guide) for the same.

I will close this issue in response to a latest Medium article regarding setup

**Comment by vincentcastagna** [comment]
Could be even more complete if we had the key.properties and the build gradle file for this wiki :)

**Comment by xeladu** [comment]
@vincentcastagna Here is a [guide](https://docs.flutter.dev/deployment/android#signing-the-app) how to create your key.properties file for Android and adapt the gradle file.

**Comment by vincentcastagna** [comment]
Thank you I have successfully done that for android. 

I'm also having trouble building iOS, signed ipa. I don't have an exportOptions.plist. Should I create it and fill it manually, or is there a way to generate it (in the xcode runner project maybe, but couldn't find anything ?).

I'm using hosted agents, and installing the prov and cert with the tasks as we usually do, but the flutter build task doesn't provide a way to pass to it the certificate installed on the machine. So I guess I absolutely need a exportOptions.plist ? 

![image](https://github.com/hey24sheep/azure-flutter-tasks/assets/15191066/cad137c1-5962-4583-bebe-258ffbb2d93f)

it tells me to open the project on a mac (which I don't have I'm using hosted agents) and sign with a development certificate. I shouldn't need to do that, I could sign it with any prov or cert I had previously installed in this pipeline job : 

```yaml
- task: InstallAppleCertificate@2
  displayName: Install certificate
  inputs:
    certSecureFile: ${{parameters.iosCertificateFile}}
    certPwd: $(CertificatePassword)

- task: InstallAppleProvisioningProfile@1
  displayName: 'Install internal provisioning profile'
  name: provisioningProfile
  inputs:
    provProfileSecureFile: ${{parameters.iosProvisioningProfileFile}}

- task: PowerShell@2
  displayName: Set the build version
  inputs:
    targetType: inline
    script: |
      $buildNumber = [int]$(git rev-list --count HEAD)
      Write-Host "##vso[task.setvariable variable=BuildNumber]$buildNumber"
      Write-Host "Build number: $BuildNumber"
    
- task: FlutterInstall@0
  displayName: "Install Flutter SDK"
  inputs:
    mode: 'auto'
    channel: 'stable'
    version: 'latest'


- task: FlutterBuild@0
  displayName: "Build application"
  inputs:
    target: 'ipa'
    buildName: '$(MajorMinorPatch)'
    buildNumber: '$(BuildNumber)'
    projectDirectory: '$(Build.SourcesDirectory)'
    verboseMode: true
    // export options is sayed optional
```
    
    
    
    Thanks

**Comment by vincentcastagna** [comment]
I have now a exportOptions.plist (was able to have a mac and export archive from xcode, then had an exportOptions, but still having trouble to get the build task to work. 

```
 Error (Xcode): No profiles for 'com.awesome.myproject' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'com.awesome.myproject'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild.
           /Users/administrator/agent/_work/12/s/ios/Runner.xcodeproj
```

 I have doubt there, because yes, it won't find a DEVELOPMENT provisioning. I have installed an Distribution one, the IPA is supposed to go on the store. This is my exportOptions
 
```
 <?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<string>app-store</string>
	<key>provisioningProfiles</key>
	<dict>
		<key>com.awesome.myproject</key>
		<string>Awesome - project</string>
	</dict>
	<key>signingCertificate</key>
	<string>Apple Distribution</string>
	<key>signingStyle</key>
	<string>manual</string>
	<key>stripSwiftSymbols</key>
	<true/>
	<key>teamID</key>
	<string>4FGZ451254CF</string>
	<key>uploadSymbols</key>
	<false/>
</dict>
</plist>
```

My yml : 

```yml
- task: DownloadSecureFile@1
  name: exportOptions
  inputs:
    secureFile: 'exportOptions.plist'

- task: FlutterBuild@0
  displayName: "Build application"
  inputs:
    target: 'ipa'
    buildName: '$(MajorMinorPatch)'
    buildNumber: '$(BuildNumber)'
    projectDirectory: '$(Build.SourcesDirectory)'
    verboseMode: true
    exportOptionsPlist: '$(exportOptions.secureFilePath)'
```
