### ISSUE TITLE
##[error]TypeError: Cannot read property 'hash' of undefined

### ISSUE THREAD

**Issue by bayysp** [hey24sheep/azure-flutter-tasks#41]
I got an issue when running flutter install on Azure,

```
Starting: Install flutter
==============================================================================
Task         : Flutter Install Task
Description  : Install the Flutter environment.
Version      : 0.3.0
Author       : Hey24sheep
Help         : For more information, take a look at the Flutter [documentation](https://flutter.io/)
==============================================================================
##[error]TypeError: Cannot read property 'hash' of undefined
Finishing: Install flutter
```
and i write this code on azure-pipeline.yml

```
- stage: pull_request
    displayName: 'Pull Request'
    condition: eq(variables['Build.Reason'], 'PullRequest')
    jobs:
      - job: build_test
        displayName: 'Build and Test for Pull Request'
        steps:
          - task: Hey24sheep.flutter.flutter-install.FlutterInstall@0
            displayName: 'Install flutter'
            inputs:
              channel: 'master'
              version: 'custom'
              customVersion: '1.22.4'
          - script: brew install lcov
            displayName: 'install lcov'
```

and here my extension console

<img width="1127" alt="Screen Shot 2022-05-23 at 13 13 22" src="https://user-images.githubusercontent.com/37262985/169754921-7fc930f8-8bba-49fe-8ee0-a0540de6d447.png">

any idea with this issue ?
