### ISSUE TITLE
Could we get an windows desktop MSIX package pipeline example?

### ISSUE THREAD

**Issue by sanketwarule** [hey24sheep/azure-flutter-tasks#48]
This is what I have tried. The Build job is succeeds, but when when the Copy task is executed it does not find any .exe file to copy.

I am able generate the MSIX package using flutter commands,
>flutter clean
>flutter pub get
>flutter build windows
>flutter pub run msix:create

Please help me in creating a MSIX package for the flutter windows desktop application

**Pre requisites:**

**In flutter pubspec.yml**

- added msix dependency
- added msix configuration
- created .pfx certificate using openssl

```
- stage: Desktop_Build
  displayName: Windows build
  jobs:
    - job: Build
      displayName: Build job
      pool:
        name: "Logistics"
        demands: "Flutter"
      steps:
        - task: Hey24sheep.flutter.flutter-build.FlutterBuild@0
          inputs:
            target: desktop (windows)
            projectDirectory: $(projectDirectory)
            buildName: "$(ipaApkName)"

        - task: CopyFiles@2
          inputs:
            sourceFolder: "$(Agent.BuildDirectory)"
            Contents: "**/*.exe"
            TargetFolder: "$(build.artifactStagingDirectory)"
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: "$(Build.ArtifactStagingDirectory)"
            ArtifactName: "drop"
            publishLocation: "Container"

```

**Comment by hey24sheep** [comment]
Hi, the issue is with your copy directory. If you read the docs on [MSIX](https://pub.dev/packages/msix) package. You will see it generates the package within `build->windows->runner->release`. "Release" could be "debug" if you are building a debug. So, update your path to this folder and you will get the copy script working. 

I am closing this issue as it is not related to this extension. I will recommend you to open this issue on [MSIX](https://github.com/YehudaKremer/msix) github so they can help you better.

**Comment by sanketwarule** [comment]
### Here is the solution that I have found
**I tried using Command line tool for creating a windows build and MSIX package of the same
Hope this will help someone, so adding a solution as closing comment**

```
- stage: Desktop_Build
    displayName: Windows build
    jobs:
      - job: Build
        displayName: Build job
        pool:
          # vmImage: 'macOS-latest'
          # vmImage: 'windows-latest'
          name: 'Logistics'
          demands: 'Flutter'
        steps:
          - task: Hey24sheep.flutter.flutter-build.FlutterBuild@0
            inputs:
              target: desktop (windows)
              projectDirectory: $(projectDirectory)
              buildName: '$(ipaApkName)'

          # - task: CmdLine@2
          #   inputs:
          #     script: |
          #       echo ----flutter doctor-----
          #       flutter doctor

          - task: CmdLine@2
            inputs:
              script: |
                echo ----flutter clean-----
                flutter clean

          - task: CmdLine@2
            inputs:
              script: |
                echo ----flutter pub get-----
                flutter pub get

          - task: CmdLine@2
            inputs:
              script: |
                echo ----flutter build windows-----
                flutter build windows

          - task: CmdLine@2
            inputs:
              script: |
                echo ----MSIX packaging-----
                flutter pub run msix:create

          - task: CopyFiles@2
            inputs:
              sourceFolder: '$(projectDirectory)'
              Contents: '**/*.msix'
              TargetFolder: '$(build.artifactStagingDirectory)'
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'drop'
              publishLocation: 'Container'

```

**Comment by moritzxbe** [comment]
Hi @hey24sheep, @sanketwarule have there been any major changes in the library? I have tested the provided code and I am getting the error "'flutter' is not recognized as an internal or external command". I am trying to execute "flutter pub run msix:create" on the windows-latest vm image. I have also tried to run the Flutter Command Task -> but I am getting the same error.

![image](https://user-images.githubusercontent.com/9870350/185383161-0ca6f79b-7ba3-4aee-9691-14e3a9b5be3d.png)

I am installing flutter using the following task:
```
- task: FlutterInstall@0
  inputs:
    mode: 'auto'
    channel: 'stable'
    version: 'latest'
```

**Comment by moritzxbe** [comment]
@hey24sheep I tried both, using cmdline command and using FlutterCommand. Unfortunately both is not working, but FlutterBuild is working.

I tried this FlutterCommand:
```
- task: FlutterCommand@0
  inputs:
    projectDirectory: '.'
    arguments: 'pub run msix:create'
```
which failed with

```
Starting: FlutterCommand
==============================================================================
Task         : Flutter Command Task
Description  : Launch a custom Flutter command with custom arguments.
Version      : 0.3.0
Author       : Hey24sheep
Help         : Don't forget to insert a 'Flutter Install' task before. [More Information](https://github.com/hey24sheep/azure-flutter-tasks)
==============================================================================
C:\Windows\system32\cmd.exe /D /S /C "C:\hostedtoolcache\windows\Flutter\3.0.5\windows\flutter\bin\flutter.bat pub run msix:create"
running "flutter build windows"...      / 

Unhandled exception:
'flutter' is not recognized as an internal or external command,
operable program or batch file.
```
I have done FlutterInstall and FlutterBuild command before, both where executed successfully.

**Comment by hey24sheep** [comment]
@moritzxbe add a "cmd" command line task to your pipeline (Not this Flutter Command task, but a CMD Task) and run this `$(FlutterToolPath)/flutter packages get` then `$(FlutterToolPath)/flutter pub run msix:create`. Let me know if that works.

**Comment by moritzxbe** [comment]
I have added those two tasks
```
- task: CmdLine@2
  inputs:
    script: |
      $(FlutterToolPath)/flutter packages get

- task: CmdLine@2
  inputs:
    script: |
      $(FlutterToolPath)/flutter pub run msix:create
```

the first one executed successfully
![image](https://user-images.githubusercontent.com/9870350/185658748-6d2e7013-2f2e-4d20-97f5-4197d76a99c4.png)

but the second failed
![image](https://user-images.githubusercontent.com/9870350/185658840-06691494-8907-4bf2-8e17-df223eae7cb2.png)


this is my complete pipeline
```
trigger:
- main

pool:
  vmImage: windows-latest

steps:

- task: FlutterInstall@0
  inputs:
    mode: 'auto'
    channel: 'stable'
    version: 'latest'

- task: DownloadSecureFile@1
  inputs:
    secureFile: 'secrets.dart'
  displayName: "Download Secret File (API Keys)"

- task: CopyFiles@2
  displayName: 'Import API Keys'
  inputs:
    SourceFolder: "$(Agent.TempDirectory)"
    Contents: "secrets.dart"
    TargetFolder: "$(Build.SourcesDirectory)/lib"

- task: FlutterBuild@0
  inputs:
    target: 'windows'
    projectDirectory: '.'
    verboseMode: true

- task: CmdLine@2
  inputs:
    script: |
      $(FlutterToolPath)/flutter packages get

- task: CmdLine@2
  inputs:
    script: |
      $(FlutterToolPath)/flutter pub run msix:create

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.SourcesDirectory)/build/windows/runner/release'
    artifact: 'release'
    publishLocation: 'pipeline'
```
