### ISSUE TITLE
Getting error while using Flutter Build Extension.

### ISSUE THREAD

**Issue by acidaes** [hey24sheep/azure-flutter-tasks#52]
I am Getting This error while using flutter build extention for iOS
error: exportArchive: No signing certificate "iOS Development" founderror: exportArchive: No signing certificate "iOS Development" found

after digging into it i found this 
(iOS).(Optional). Set iosCodesign to configure whenever the bundle odesign the application bundle (only available on device builds, and activated by default). Warning: you must install a valid certificate before build with the Install an Apple Certificatetask
but the above option is not available in the task.

can some one  help into it.

Thanks in Advance.

**Comment by hey24sheep** [comment]
This error is your configuration issue from your side. It is telling you that signing certificates are missing.

As you have not provided any details regarding your setup/config. So I am assuming you are missing this `iosCodesign: false`. 

Here is how your YAML should look like for IOS Build (`flutter build ios`)

```yaml
steps:
- task: Hey24sheep.flutter.flutter-build.FlutterBuild@0
  displayName: 'Flutter Build ios'
  inputs:
    target: ios
    projectDirectory: myproject
    buildFlavour: development
    buildNumber: '$(Build.BuildNumber)'
    entryPoint: 'lib/main_dev.dart'
    iosCodesign: false
```

After that use these tasks, [Apple Cert Task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/install-apple-certificate?view=azure-devops) and then [Apple Provision Profile](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/install-apple-provisioning-profile?view=azure-devops)
