### ISSUE TITLE
How to correctly configure CFBundleVersion and CFBundleShortVersionString and 

### ISSUE THREAD

**Issue by shadyaziza** [hey24sheep/azure-flutter-tasks#58]
I do not quite get the part where I can change my version name and pump the build number. I would expect the final build reflects the following, I can see in the logs of `flutter build` that the values are correct. However, it seems that the deployed version always
have `0.1.0` as version name and `1` as build number.

```swift
<key>CFBundleVersion</key>
<string>6</string>
<key>CFBundleShortVersionString</key>
<string>$(FLUTTER_BUILD_NAME)</string>
```
```yaml
   - task: FlutterBuild@0
      displayName: Build iOS
      inputs:
        target: 'ios'
        projectDirectory: '.'
        verboseMode: true
        buildFlavour: 'development'
        buildNumber: '$(BUILD_BUILDNUMBER)'
        buildName: '$(buildTimeStamp)'
        exportOptionsPlist: 'ios/exportOptions.plist'
        iosCodesign: false

   - task: CopyFiles@2
      inputs:
        contents: '**/*.ipa'
        targetFolder: '$(build.artifactStagingDirectory)'

   - task: PublishBuildArtifacts@1
      inputs:
       PathtoPublish: '$(Build.ArtifactStagingDirectory)'
       ArtifactName: 'drop'
       publishLocation: 'Container'
    
   - task: AppCenterDistribute@3
      inputs:
        serverEndpoint: 'App Center'
        appSlug: <slug>
        appFile: '$(build.artifactstagingdirectory)/**/*.ipa'
        releaseNotesOption: 'input'
        releaseNotesInput: '- QA Release'
        destinationType: 'groups'
        distributionGroupId: <group_id>
```
