### ISSUE TITLE
Flutter install problem with older version found in cache

### ISSUE THREAD

**Issue by Elineusz** [hey24sheep/azure-flutter-tasks#67]
Hi!

Thank you for great tool.

Unfortunately I encounter a problem. Some of my pipeline runs are negative because older version of Flutter is found in cache. ( I did not created it myself, MS did it) 
Install tool do not install targeted version if older one is found.  

Variable:

```
  - name: flutter-version
    value: '3.7.0'
    
```
    
Pipeline task:

```
    - task: FlutterInstall@0
      inputs:
        mode: 'auto'
        channel: 'stable'
        version: 'custom'
        customVersion: $(flutter-version)

```

Result:

```
Starting: FlutterInstall
==============================================================================
Task         : Flutter Install Task
Description  : Install the Flutter environment.
Version      : 0.3.5
Author       : Hey24sheep
Help         : For more information, take a look at the Flutter [documentation](https://flutter.io/)
==============================================================================
Found tool in cache: Flutter 3.3.1 windows
Finishing: FlutterInstall

```
