### ISSUE TITLE
Android Gradle plugin requires Java 11 to run. You are currently using Java 1.8.

### ISSUE THREAD

**Issue by LynoDesu** [hey24sheep/azure-flutter-tasks#69]
Hi,

Just wanted to try setting up a test pipeline using this plugin and I get this error:

```
* Where:
Build file '/Users/runner/work/1/s/android/app/build.gradle' line: 24

* What went wrong:
A problem occurred evaluating project ':app'.
> Failed to apply plugin 'com.android.internal.application'.
   > Android Gradle plugin requires Java 11 to run. You are currently using Java 1.8.
     Your current JDK is located in  /Users/runner/hostedtoolcache/Java_Temurin-Hotspot_jdk/8.0.362-9/x64/Contents/Home/jre
     You can try some of the following options:
       - changing the IDE settings.
       - changing the JAVA_HOME environment variable.
       - changing `org.gradle.java.home` in `gradle.properties`.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org/

BUILD FAILED in 57s
Running Gradle task 'assembleRelease'...                           59.0s

┌─ Flutter Fix ─────────────────────────────────────────────────────────────────┐
│ [!] You need Java 11 or higher to build your app with this version of Gradle. │
│                                                                               │
│ To get Java 11, update to the latest version of Android Studio on             │
│ https://developer.android.com/studio/install.                                 │
│                                                                               │
│ To check the Java version used by Flutter, run `flutter doctor -v`.           │
└───────────────────────────────────────────────────────────────────────────────┘
Gradle task assembleRelease failed with exit code 1
##[error]Error: The process '/Users/runner/hostedtoolcache/Flutter/3.7.5/macos/flutter/bin/flutter' failed with exit c
```

Here's my very simple pipeline:

```
jobs:
  - job: Android
    pool:
      vmImage: 'macOS-latest'
    steps:
    - task: FlutterInstall@0
    - task: FlutterBuild@0
      inputs:
        target: apk
        projectDirectory: '.'
    - task: FlutterTest@0
      inputs:
        projectDirectory: '.'
    - task: CopyFiles@2
      inputs:
        contents: '**/*.apk'
        targetFolder: '$(build.artifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
```
