### ISSUE TITLE
Target file "--no-sound-null-safety --no-tree-shake-icons" not found.

### ISSUE THREAD

**Issue by eric2788** [hey24sheep/azure-flutter-tasks#93]
```yaml
- task: FlutterBuild@0
   inputs:
      target: 'mobile'
      projectDirectory: '.'
      buildNumber: '$(BUILD_NUM)'
      buildName: '$(VERSION)'
      extraArgs: '--no-sound-null-safety --no-tree-shake-icons'
      apkTargetPlatform: 'android-arm64'
      iosCodesign: false
```

got
 
```bash
Target file "--no-sound-null-safety --no-tree-shake-icons" not found.
```

downgraded to 0.3.6 solve the problem.
