### ISSUE TITLE
`buildName` doesn't pass `--build-name` to the command

### ISSUE THREAD

**Issue by Zazo032** [hey24sheep/azure-flutter-tasks#96]
Build task:
```yml
        - task: FlutterBuild@0
          displayName: 'Build Web'
          inputs:
            buildName: '$(versionName)'
            dartDefine: 'app.flavor=qa'
            projectDirectory: '.'
            target: 'web'
```

Task output:
```
Starting: Build Web
==============================================================================
Task         : Flutter Build Task
Description  : Build a Flutter application project.
Version      : 0.3.9
Author       : Hey24sheep
Help         : [More Information](https://github.com/hey24sheep/azure-flutter-tasks)
==============================================================================
/opt/hostedtoolcache/flutter/bin/flutter build web --dart-define=app.flavor=qa
```
