### ISSUE TITLE
Variable `FlutterPubCachePath` provides an empty directory

### ISSUE THREAD

**Issue by Zazo032** [hey24sheep/azure-flutter-tasks#99]
Pipeline:

```yaml
  - task: Cache@2
    displayName: 'Cache Flutter'
    inputs:
      cacheHitVar: FLUTTER_CACHED
      key: 'flutter | stable | $(Agent.OS)'
      path: $(Agent.ToolsDirectory)/flutter

  - task: FlutterEnv@0
    condition: eq(variables.FLUTTER_CACHED, 'true')
    displayName: 'Setup Flutter'
    inputs:
      customPath: '$(Agent.ToolsDirectory)/flutter'
      pathType: 'customPath'

  - task: FlutterInstall@0
    condition: eq(variables.FLUTTER_CACHED, 'false')
    displayName: 'Install Flutter'
    inputs:
      channel: 'stable'
      mode: 'auto'
      version: 'latest'

  - task: CmdLine@2
    displayName: 'Dart: Pub get'
    inputs:
      failOnStderr: true
      script: 'dart pub get'

  - task: CmdLine@2
    displayName: 'Pub cache path (task)'
    inputs:
      script: 'echo $(FlutterPubCachePath)'

  - task: CmdLine@2
    displayName: 'Pub cache files (task)'
    inputs:
      script: 'ls -a $(FlutterPubCachePath)'
```

The output of `Pub cache path (task)`:
```console
/opt/hostedtoolcache/flutter/.pub-cache
```

The output of `Pub cache files (task)`:
```console
ls: cannot access '/opt/hostedtoolcache/flutter/.pub-cache': No such file or directory
##[error]Bash exited with code '2'.
```

Seems like the returned path from `FlutterPubCachePath` is wrong or `dart pub get` is not saving the packages in that directory
